language: objective-c
osx_image: xcode8.2
script:
  - xcodebuild -workspace Localize.xcworkspace -scheme LocalizeTests -sdk iphonesimulator10.2 -destination "OS=10.2,name=iPhone 7 Plus" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;